In [1]:
import numpy as np

In [24]:
a=np.array([3,4,5,6,4])
a

array([3, 4, 5, 6, 4])

In [9]:
def show_arr(arr):
 print(a.shape)
 print(a.size)
 print(a.dtype)
 len(a)
 print(a.ndim)

In [31]:
b= np.array([[[10,100],[11,110],[13,130],[14,140]],#fetch(2*2*2)
             [[45,145],[22,122],[9,19],[2,12]],#fetch(1*2*2),fetch(2*1*1)
             [[6,16],[5,15],[1,11],[8,18]]])#comma seperted is rows , fetch(3*1*1)
b
show_arr(a)
b.ndim

(5,)
5
int32
1


3

In [15]:
#array operation
# item accessing-subscripting, slicing
# item assignment
# item insertino
# item deletion
# arithmetic

In [32]:
c=np.array([[10,11,13,14],[45,22,9,2],[6,5,1,8]])#fetch (1*4)
#subrscripting-accessing from 3d [1st:1st end: stepsize, 2nd,3rd]
c[0,0]
c[1, -3:]
c[:, -2]
c[:, -2:-1]

array([[13],
       [ 9],
       [ 1]])

In [30]:
c[:, -2].shape

(3,)

In [34]:
#ans-
#1*4
print(c[-1:,:1])
#1*2*2-
print(b[:1,:2,:1])
#3*1*1
print(b[:,1:2,:1])
#2*1*1
print(b[-2:, -1:,:1])
#2*2*2
print(b[:2,-2:, :])


[[6]]
[[[10]
  [11]]]
[[[11]]

 [[22]]

 [[ 5]]]
[[[2]]

 [[8]]]
[[[ 13 130]
  [ 14 140]]

 [[  9  19]
  [  2  12]]]


In [37]:
#item assignment
c[1,2]=90
c

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [42]:
#item insertion
#1d
a=np.append(a,80)
a
#2d
np.append(c,[[9,90,900,9000]],axis=0)#axis 0 = row, 1->column


array([[  10,   11,   13,   14],
       [  45,   22,   90,    2],
       [   6,    5,    1,    8],
       [   9,   90,  900, 9000]])

In [45]:

np.append(c,[[9],[90],[900]],axis=1)

array([[ 10,  11,  13,  14,   9],
       [ 45,  22,  90,   2,  90],
       [  6,   5,   1,   8, 900]])

In [48]:
#deletion, #single element cannot be deleted
c
c1=c.copy()

In [49]:
np.delete(c1, 0, axis=0)

array([[45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [50]:
#arithmetic operations
c1-20

array([[-10,  -9,  -7,  -6],
       [ 25,   2,  70, -18],
       [-14, -15, -19, -12]])

In [51]:
c1+20

array([[ 30,  31,  33,  34],
       [ 65,  42, 110,  22],
       [ 26,  25,  21,  28]])

In [52]:
c1*2

array([[ 20,  22,  26,  28],
       [ 90,  44, 180,   4],
       [ 12,  10,   2,  16]])

In [56]:
#array manupiplation
#arr reshape
c1.reshape(2,6,1)

array([[[10],
        [11],
        [13],
        [14],
        [45],
        [22]],

       [[90],
        [ 2],
        [ 6],
        [ 5],
        [ 1],
        [ 8]]])

In [57]:
#arr.astype()
c1.astype(float)

array([[10., 11., 13., 14.],
       [45., 22., 90.,  2.],
       [ 6.,  5.,  1.,  8.]])

In [58]:
c1.astype('uint16')

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]], dtype=uint16)

In [59]:
#more functions to create array
#np.array()
#np.arange()->array version of range func, also allows float
#np.linspace()->start,end,no. of items
#np.ones()->generate all values as '1'
#np.zeroes()->generate all values
#np.random.random()
#mp.random.randint()

In [61]:
np.ones((3,4),dtype='int')*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])